# Generated by Django 3.1.1 on 2020-09-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200923_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='status',
            new_name='is_active',
        ),
    ]
